trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-ap'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |

      az deployment group create \
        --resource-group RG-User01 \
        --template-file main.bicep \
        --parameters @parameters.json

- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-ap'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |

      INSTANCE_IDS=$(az vmss list-instances \
        --resource-group RG-User01 \
        --name myecomm-vmss \
        --query "[].instanceId" \
        -o tsv)

      for id in $INSTANCE_IDS
      do

        echo "Deploying to instance: $id"

        az vmss run-command invoke \
          --resource-group RG-User01 \
          --name myecomm-vmss \
          --instance-id $id \
          --command-id RunShellScript \
          --scripts "

            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -

            sudo apt-get install -y nodejs git

            sudo npm install -g pm2

            cd /home/azureuser

            sudo rm -rf myecomm-app

            git clone https://github.com/martial-sudo/myecomm-app.git

            cd myecomm-app

            npm install

            pm2 delete all || true

            pm2 start app.js

            pm2 startup systemd -u azureuser --hp /home/azureuser

            pm2 save
          "

      done
